- name: Stop an instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-8dbc7e0f'
    region: sa-east-1
  tasks:
    - name: Stopping the instance
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: subnet-9e630ffa
        assign_public_ip: no
