- name: Stop AWS instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-xxxxxxxx'
      - 'i-xxxxxxxx'
      - 'i-xxxxxxxx'
      - 'i-xxxxxxxx'
    region: sa-east-1
    vpc_subnet_id: subnet-xxxxxxxx
  tasks:
    - name: Stopping AWS instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: '{{vpc_subnet_id}}'
        assign_public_ip: yes
