- name: Start instance
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Start the instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: '{{ vpc_subnet_id }}'
        assign_public_ip: no
