- name: Stop an instance
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Stopping the instance
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: '{{ vpc_subnet_id }}'
        assign_public_ip: no
