- name: Eliminando una aplicación en OpenShift Online
  hosts: all
  user: centos
  gather_facts: false
  connection: local
    tasks:
        - name: Conexion a OpenShift Online
          command: oc login --username={{user}} --password={{password}} --insecure-skip-tls-verify --server={{server}}:8443

        - name: Eliminando Aplicacion en OpenShift Online
          command: oc delete project {{project_name}}
